Traceback (most recent call last):
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/richard/.virtualenvs/etcdocs/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import altair as alt
import numpy as np

ranges = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
charts = []
hcharts = []
count = 0

for dept_code in depts:
  dept_diff_rows_df = pd.DataFrame()
  dept_cur_stats_df = tidied_cur_month_df.loc[tidied_cur_month_df[' collectionCode'] == dept_code]
  dept_last_stats_df =  tidied_last_month_df.loc[tidied_last_month_df[' collectionCode'] == dept_code]

  if(len(dept_cur_stats_df) < 10):
        continue
    
  # Now need to loop over each completeness coll in turn
  for cur_column, last_column in zip(dept_cur_stats_df.columns[1:], dept_last_stats_df.columns[1:]):
    
    cur_dept_col_counts = dept_cur_stats_df[cur_column].groupby(pd.cut(dept_cur_stats_df[cur_column], ranges, labels=["0-10%","10-20%","20-30%","30-40%","40-50%","50-60%","60-70%","70-80%","80-90%","90-100%"], include_lowest=True)).count()
    last_dept_col_counts = dept_last_stats_df[last_column].groupby(pd.cut(dept_last_stats_df[last_column], ranges, labels=["0-10%","10-20%","20-30%","30-40%","40-50%","50-60%","60-70%","70-80%","80-90%","90-100%"], include_lowest=True)).count()
    diff_dept_col_counts = cur_dept_col_counts.subtract(last_dept_col_counts, fill_value=0)
    
    dept_diff_rows_df = dept_diff_rows_df.append(diff_dept_col_counts, ignore_index=False)
    
  dept_diff_rows_df = dept_diff_rows_df.rename_axis('Concept').rename_axis('Percentages', axis='columns')
    # TO handle converting from CategoricalIndex - may change https://github.com/pandas-dev/pandas/issues/19136
  dept_diff_rows_df.columns = dept_diff_rows_df.columns.tolist()
  dept_diff_rows_df = dept_diff_rows_df.reset_index()
  dept_diff_rows_melt_df = dept_diff_rows_df.melt(id_vars=['Concept'], var_name='Percentage', value_name='Change')
  
  # Replace zero values with Nan so altair doesn't show them
    
  dept_diff_rows_melt_df.replace(0, np.nan, inplace=True)

  chart = alt.Chart(dept_diff_rows_melt_df).mark_circle().encode(
    alt.X('Percentage:O'),
    alt.Y('Concept:O'),
    alt.Size('Quantity:Q'),
    alt.Color('Direction:N', scale=alt.Scale(domain=['Fewer Records', 'More Records'], range=['red', 'green'])),
    tooltip=['Change']
  ).transform_calculate(
      Quantity='abs(datum.Change)',
      Direction='if(datum.Change < 0, "Fewer Records", "More Records")'
  ).properties(title="%s" % (deptNames[dept_code]), width=300)
    
  charts.append(chart)
  if count > 0:
      hcharts.append(alt.hconcat(*charts))
      charts = []
      count = 0
  else:
      count += 1

hcharts.append(alt.hconcat(*charts))

alt.vconcat(*hcharts)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-9-a60b1702585c>[0m in [0;36m<module>[0;34m[0m
[1;32m     43[0m       [0mQuantity[0m[0;34m=[0m[0;34m'abs(datum.Change)'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     44[0m       [0mDirection[0m[0;34m=[0m[0;34m'if(datum.Change < 0, "Fewer Records", "More Records")'[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 45[0;31m   ).properties(title="%s" % (deptNames[dept_code]), width=300)
[0m[1;32m     46[0m [0;34m[0m[0m
[1;32m     47[0m   [0mcharts[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mchart[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'T&P'
KeyError: 'T&P'

